#!/usr/bin/env python3
"""Generate single-point proteus grid configs for interrupted grid points.

Purpose: recovering from the department cluster's weekly reset (every
Sunday at midnight, kills any jobs on any machine cluster-wide), or any
other event that kills a batch mid-run without a clean finish. It is NOT
for launching never-yet-attempted points from batch03..batch16 -- those
should go through the normal, more efficient 64-point batch configs in
grid_sweep_configs/batch_configs/ as originally planned. This script is
specifically for points that were *attempted* (a case directory exists
somewhere, live or harvested) and got killed before finishing, so their
data/log is incomplete and needs a fresh attempt.

Why one config per point, not a multi-value batch config
-----------------------------------------------------------------------
`proteus grid` always runs the full Cartesian product of whatever
per-axis "direct"/"logspace"/etc. value lists a config gives it (see
scripts/harvest_completed_cases.py's own docstring, and
PROTEUS/src/proteus/grid/manage.py Grid.generate()). An arbitrary,
scattered set of interrupted grid points essentially never forms a clean
rectangular sub-grid, so the only way to express "resume exactly these N
points, and nothing else" in the existing config format is N separate
single-point configs (each axis's "direct" list has exactly one value,
so the grid size is 1). Bundling several points into one multi-value
config would silently also (re-)run every OTHER combination of those
axis values -- including points that already succeeded.

What counts as "needs a fresh attempt"
-----------------------------------------------------------------------
For every grid point in the full 1024-point sweep, this script determines
one of:
  - success: a `..._1_success` folder already exists in simulation_data/
    -> done, never regenerated.
  - active: a case for this point is sitting in a currently-launched
    batch's directory (grid_sweep_configs/batch_configs/batch*.toml) and
    is confirmed genuinely alive via the same SSH-based liveness check as
    harvest_completed_cases.py -> in progress, left alone.
  - crashed: a `..._2_fatal_crash_*` or `..._3_crash_*` folder exists (in
    simulation_data/, or found sitting in a live batch dir and classified
    as a crash by the same log-cross-checking logic) -> a genuine code/
    physics failure, most likely reproducible, so NOT regenerated by
    default (would waste compute repeating a deterministic crash) --
    reported separately; use --include-crashed to regenerate these too.
  - killed: found dead with no traceback and no clean finish (either
    already harvested to simulation_data/ as `..._6_unclassified`, or
    found sitting in a live batch dir but confirmed no longer alive) ->
    genuinely interrupted mid-run (a cluster reset, SIGKILL, OOM, node
    reboot, ...), safe and useful to regenerate -- this is the default
    target of this script.
  - never attempted: no case directory exists anywhere for this point
    (normal for batch03..batch16, not yet launched) -> reported
    separately, NOT regenerated by default (use the planned batch
    configs for these instead); --include-never-attempted to override.

Output
-----------------------------------------------------------------------
Writes one `batch_gapfill_H<i>_C<i>_N<i>_S<i>_fO2<i>.toml` per targeted
point into a fresh timestamped directory under
grid_sweep_configs/gapfill_configs/, each a valid `proteus grid` config
(grid size 1, symlink="" per the current workaround for the disabled
symlink field -- see CLAUDE.md) pointing at the same fiducial ref_config
as every other config in this project. Also writes a `launch.sh` helper
(bounded-concurrency launcher for a single machine) into the same
directory. Nothing is launched automatically -- this script only
prepares the configs; launching real cluster jobs remains a deliberate,
separate step (see grid_sweep_cluster_howto.md "Steps to launch a
sweep"). To check on / harvest gap-fill results later, point
harvest_completed_cases.py at this directory:
    python3 scripts/harvest_completed_cases.py --batch-configs <this-output-dir>

Usage:
    python scripts/generate_gapfill_configs.py [--include-crashed]
        [--include-never-attempted] [--report-only]

Example:
    python scripts/generate_gapfill_configs.py
"""

from __future__ import annotations

import argparse
import itertools
import re
import sys
import time
from datetime import datetime
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))
import harvest_completed_cases as hc  # noqa: E402  (needs sys.path set up first)

PROJECT_ROOT = SCRIPT_DIR.parent
DEFAULT_GAPFILL_ROOT = PROJECT_ROOT / "grid_sweep_configs" / "gapfill_configs"

AXIS_ORDER = ("H", "C", "N", "S", "fO2")

GRID_NAME_RE = re.compile(r"^grid_H(\d+)_C(\d+)_N(\d+)_S(\d+)_fO2(\d+)__")


def full_grid_indices(full_axes: dict[str, list[float]]) -> list[tuple[int, ...]]:
    """Every (h, c, n, s, fO2) index-tuple in the full sweep, in AXIS_ORDER."""
    ranges = [range(len(full_axes[axis])) for axis in AXIS_ORDER]
    return list(itertools.product(*ranges))


def parse_harvested_folder(name: str) -> tuple[tuple[int, ...], str] | None:
    """Extract (index_tuple, outcome_tag) from a simulation_data/ folder name."""
    m = GRID_NAME_RE.match(name)
    if not m:
        return None
    indices = tuple(int(g) for g in m.groups())
    outcome_tag = name.rsplit("__", 1)[-1]
    return indices, outcome_tag


def classify_outcome_tag(outcome_tag: str) -> str:
    """Bucket an outcome_tag string into 'success' | 'crashed' | 'killed' | 'other'."""
    if outcome_tag == hc.ag.CATEGORY_LABELS[1]:
        return "success"
    for cat in (2, 3):
        label = hc.ag.CATEGORY_LABELS[cat]
        if outcome_tag == label or outcome_tag.startswith(label + "_"):
            return "crashed"
    if outcome_tag == hc.ag.CATEGORY_LABELS[6]:
        return "killed"
    return "other"


def scan_simulation_data(dest_dir: Path) -> dict[tuple[int, ...], str]:
    """{index_tuple: bucket} for every already-harvested point, best-outcome-wins
    if a point was attempted more than once (success always wins)."""
    resolved: dict[tuple[int, ...], str] = {}
    if not dest_dir.is_dir():
        return resolved
    for entry in dest_dir.iterdir():
        if not entry.is_dir():
            continue
        parsed = parse_harvested_folder(entry.name)
        if parsed is None:
            continue
        indices, outcome_tag = parsed
        bucket = classify_outcome_tag(outcome_tag)
        if resolved.get(indices) != "success":
            resolved[indices] = bucket
    return resolved


def scan_active_batches(
    batch_configs_dir: Path,
    proteus_output: Path,
    full_axes: dict[str, list[float]],
    machines: tuple[str, ...],
    ssh_timeout: float,
) -> dict[tuple[int, ...], str]:
    """{index_tuple: bucket} for every case currently sitting in a live batch
    directory -- 'active' if genuinely still running (never targeted for
    regeneration), otherwise classified the same way as a harvested folder
    would be (success/crashed/killed), in case harvest_completed_cases.py
    hasn't been run recently and a finished-or-dead case is still sitting
    in its original batch directory.
    """
    resolved: dict[tuple[int, ...], str] = {}
    batches = hc.discover_batches(batch_configs_dir, proteus_output)
    if not batches:
        return resolved

    now = time.time()
    live_lines, unreachable = hc.query_live_process_lines(machines, ssh_timeout)
    if unreachable:
        print(
            f"warning: could not reach {len(unreachable)} machine(s) via SSH: "
            f"{', '.join(unreachable)} -- their active cases may be misjudged "
            "for this run (same caveat as harvest_completed_cases.py)",
            file=sys.stderr,
        )

    for _batch_name, output_name, source_dir in batches:
        if not source_dir.is_dir():
            continue
        case_dirs = sorted(
            p for p in source_dir.iterdir() if p.is_dir() and p.name.startswith("case_")
        )
        for case_dir in case_dirs:
            params = hc.read_case_params(case_dir)
            if params is None:
                continue  # no init_coupler.toml yet -- too early to have a grid position
            indices = []
            ok = True
            for axis in AXIS_ORDER:
                idx = hc.match_index(params[axis], full_axes[axis])
                if idx is None:
                    ok = False
                    break
                indices.append(idx)
            if not ok:
                continue
            indices_t = tuple(indices)

            category, _outcome, _sig, _status = hc.determine_real_outcome(
                case_dir, output_name, live_lines, now
            )
            if category in (4, 5):
                resolved[indices_t] = "active"
            elif category == 1:
                if resolved.get(indices_t) != "success":
                    resolved[indices_t] = "success"
            elif category in (2, 3):
                if resolved.get(indices_t) not in ("success", "active"):
                    resolved[indices_t] = "crashed"
            else:  # category 6
                if resolved.get(indices_t) not in ("success", "active", "crashed"):
                    resolved[indices_t] = "killed"
    return resolved


def merge_resolutions(
    simdata: dict[tuple[int, ...], str], active_batches: dict[tuple[int, ...], str]
) -> dict[tuple[int, ...], str]:
    """Combine both scans; 'active' and 'success' always take priority."""
    merged = dict(simdata)
    for indices, bucket in active_batches.items():
        current = merged.get(indices)
        if current in ("success", "active"):
            continue
        if bucket in ("success", "active") or current is None:
            merged[indices] = bucket
    return merged


def write_gapfill_config(
    output_dir: Path, indices: tuple[int, ...], full_axes: dict[str, list[float]], reason: str
) -> Path:
    h, c, n, s, f = indices
    values = {axis: full_axes[axis][idx] for axis, idx in zip(AXIS_ORDER, indices)}
    name = f"batch_gapfill_H{h}_C{c}_N{n}_S{s}_fO2{f}"

    content = f"""# Gap-fill config for grid point H{h}_C{c}_N{n}_S{s}_fO2{f}
# Generated by scripts/generate_gapfill_configs.py on {datetime.now().isoformat(timespec="seconds")}
# Reason: {reason}
#
# Single-point proteus grid config (grid size 1), not a multi-value batch --
# see this project's generate_gapfill_configs.py docstring for why an
# arbitrary/scattered set of missing points can't be expressed as one
# multi-value grid config (proteus grid always takes the full Cartesian
# product of whatever per-axis values it's given).
#
# `symlink` is blank -- see the batch configs in grid_sweep_configs/batch_configs/
# for why (a confirmed PROTEUS bug; real data lands directly under
# PROTEUS/output/<name>/ until fixed upstream).

output = "{name}/"
symlink = ""

ref_config = "input/nogit_k218b_project/k218b_fiducial.toml"

use_slurm = false
max_jobs = 500
max_days = 1
max_mem  = 3

["planet.elements.H_budget"]
    method = "direct"
    values = [{values["H"]!r}]

["planet.elements.C_budget"]
    method = "direct"
    values = [{values["C"]!r}]

["planet.elements.N_budget"]
    method = "direct"
    values = [{values["N"]!r}]

["planet.elements.S_budget"]
    method = "direct"
    values = [{values["S"]!r}]

["outgas.fO2_shift_IW"]
    method = "direct"
    values = [{float(values["fO2"])!r}]
"""
    path = output_dir / f"{name}.toml"
    path.write_text(content)
    return path


LAUNCH_SCRIPT_TEMPLATE = """#!/bin/bash
# Launch every batch_gapfill_*.toml config in this directory on ONE machine,
# bounded to at most MAXJOBS concurrent `proteus grid` invocations (each
# manages exactly 1 case, since these are single-point configs).
#
# Run this from inside an already-activated proteus conda env, on the
# target machine -- e.g. via a detached tmux session (see
# grid_sweep_cluster_howto.md "Steps to launch a sweep"):
#   ssh <machine> "tmux new-session -d -s gapfill -c /data/rdc49-2/PROTEUS \\
#     && tmux send-keys -t gapfill 'module load netcdf/4-2025.01' C-m \\
#     && sleep 2 \\
#     && tmux send-keys -t gapfill 'conda activate proteus' C-m \\
#     && sleep 3 \\
#     && tmux send-keys -t gapfill 'bash {launch_script_path} <max_jobs>' C-m"
#
# Usage: bash launch.sh [max_concurrent_jobs]
set -e
DIR="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
MAXJOBS="${{1:-24}}"
cd /data/rdc49-2/PROTEUS

shopt -s nullglob
configs=("$DIR"/batch_gapfill_*.toml)
if [ ${{#configs[@]}} -eq 0 ]; then
    echo "No batch_gapfill_*.toml configs found in $DIR"
    exit 1
fi

echo "Launching ${{#configs[@]}} gap-fill point(s), up to $MAXJOBS concurrently..."
for cfg in "${{configs[@]}}"; do
    while [ "$(jobs -rp | wc -l)" -ge "$MAXJOBS" ]; do
        wait -n
    done
    nice -n 19 proteus grid -c "$cfg" > "${{cfg%.toml}}.launch.log" 2>&1 &
done
wait
echo "All gap-fill point(s) finished. Check status with:"
echo "  python3 /data/rdc49-2/K218b_project/scripts/harvest_completed_cases.py --batch-configs $DIR"
"""


def write_launch_script(output_dir: Path) -> Path:
    path = output_dir / "launch.sh"
    path.write_text(LAUNCH_SCRIPT_TEMPLATE.format(launch_script_path=path))
    path.chmod(0o755)
    return path


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--full-sweep", type=Path, default=hc.DEFAULT_FULL_SWEEP,
        help=f"Full parameter sweep config (default: {hc.DEFAULT_FULL_SWEEP})",
    )
    parser.add_argument(
        "--batch-configs", type=Path, default=hc.DEFAULT_BATCH_CONFIGS,
        help="Directory of the *planned* batch*.toml configs to scan for "
        f"currently-active cases (default: {hc.DEFAULT_BATCH_CONFIGS})",
    )
    parser.add_argument(
        "--proteus-output", type=Path, default=hc.DEFAULT_PROTEUS_OUTPUT,
        help=f"PROTEUS output directory (default: {hc.DEFAULT_PROTEUS_OUTPUT})",
    )
    parser.add_argument(
        "--dest", type=Path, default=hc.DEFAULT_SIMULATION_DATA,
        help=f"Where harvested results live (default: {hc.DEFAULT_SIMULATION_DATA})",
    )
    parser.add_argument(
        "--output-dir", type=Path, default=None,
        help="Where to write the gap-fill configs (default: a fresh timestamped "
        f"directory under {DEFAULT_GAPFILL_ROOT})",
    )
    parser.add_argument(
        "--include-crashed", action="store_true",
        help="Also regenerate configs for genuinely crashed points (off by default: "
        "a code/physics crash is likely to reproduce identically, so blindly "
        "retrying wastes compute -- investigate before including these)",
    )
    parser.add_argument(
        "--include-never-attempted", action="store_true",
        help="Also regenerate configs for points that have never been attempted at "
        "all (off by default: use the planned batch configs for these instead, "
        "they're far more efficient than one-point-per-config)",
    )
    parser.add_argument(
        "--report-only", action="store_true",
        help="Print the breakdown but don't write any config files",
    )
    parser.add_argument(
        "--machines", type=lambda s: tuple(m.strip() for m in s.split(",") if m.strip()),
        default=hc.DEFAULT_MACHINES,
        help=f"Cluster machines to check for active cases (default: all "
        f"{len(hc.DEFAULT_MACHINES)} known machines)",
    )
    parser.add_argument(
        "--ssh-timeout", type=float, default=hc.DEFAULT_SSH_TIMEOUT,
        help=f"SSH connect timeout per machine (default: {hc.DEFAULT_SSH_TIMEOUT})",
    )
    args = parser.parse_args()

    full_axes = hc.load_full_grid_axes(args.full_sweep)
    all_indices = full_grid_indices(full_axes)

    simdata_resolved = scan_simulation_data(args.dest)
    active_resolved = scan_active_batches(
        args.batch_configs, args.proteus_output, full_axes, args.machines, args.ssh_timeout
    )
    resolved = merge_resolutions(simdata_resolved, active_resolved)

    buckets: dict[str, list[tuple[int, ...]]] = {
        "success": [], "active": [], "crashed": [], "killed": [], "never_attempted": [],
    }
    for indices in all_indices:
        bucket = resolved.get(indices, "never_attempted")
        buckets[bucket].append(indices)

    print("=" * 70)
    print("Grid point status (out of %d total)" % len(all_indices))
    print("=" * 70)
    for name in ("success", "active", "crashed", "killed", "never_attempted"):
        print(f"  {name}: {len(buckets[name])}")
    print("-" * 70)

    targets = list(buckets["killed"])
    if args.include_crashed:
        targets += buckets["crashed"]
    if args.include_never_attempted:
        targets += buckets["never_attempted"]

    if not targets:
        print("Nothing to regenerate (no killed points" +
              ("" if args.include_crashed else ", crashed points excluded by default") +
              ("" if args.include_never_attempted else ", never-attempted points excluded by default") +
              ").")
        print("=" * 70)
        return 0

    print(f"Targeting {len(targets)} point(s) for gap-fill config generation:")
    print(f"  killed (always included): {len(buckets['killed'])}")
    print(f"  crashed ({'included' if args.include_crashed else 'excluded'} by default): {len(buckets['crashed'])}")
    print(f"  never attempted ({'included' if args.include_never_attempted else 'excluded'} by default): {len(buckets['never_attempted'])}")

    if args.report_only:
        print("--report-only: not writing any config files.")
        print("=" * 70)
        return 0

    output_dir = args.output_dir or (
        DEFAULT_GAPFILL_ROOT / datetime.now().strftime("%Y%m%d_%H%M%S")
    )
    output_dir.mkdir(parents=True, exist_ok=True)

    reason_by_bucket = {
        "killed": "found dead with no traceback/clean finish (e.g. cluster reset, SIGKILL, OOM)",
        "crashed": "genuine crash on the previous attempt (--include-crashed)",
        "never_attempted": "never attempted before (--include-never-attempted)",
    }
    bucket_of = {}
    for name in ("killed", "crashed", "never_attempted"):
        for indices in buckets[name]:
            bucket_of[indices] = name

    written = []
    for indices in targets:
        reason = reason_by_bucket[bucket_of[indices]]
        written.append(write_gapfill_config(output_dir, indices, full_axes, reason))
    launch_path = write_launch_script(output_dir)

    print(f"\nWrote {len(written)} config(s) and a launcher to: {output_dir}")
    print(f"Launch on a chosen machine with, e.g.:")
    print(f"  ssh <machine> \"tmux new-session -d -s gapfill -c /data/rdc49-2/PROTEUS \\")
    print(f"    && tmux send-keys -t gapfill 'module load netcdf/4-2025.01' C-m \\")
    print(f"    && sleep 2 && tmux send-keys -t gapfill 'conda activate proteus' C-m \\")
    print(f"    && sleep 3 && tmux send-keys -t gapfill 'bash {launch_path} <max_jobs>' C-m\"")
    print(f"Check progress/harvest results with:")
    print(f"  python3 scripts/harvest_completed_cases.py --batch-configs {output_dir}")
    print("=" * 70)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
