#!/usr/bin/env bash
#
# launch_vulcan_reruns.sh -- launch the per-machine launch_<machine>.sh
# scripts generated by scripts/generate_vulcan_rerun_configs.py across the
# cluster, one detached tmux session per machine, following the same
# busy-check + staggered-SSH-launch conventions as scripts/launch_batches.sh
# (see that script and grid_sweep_cluster_howto.md for the underlying manual
# procedure). This is a trimmed adaptation, not a rewrite: it drops
# launch_batches.sh's output-directory clobber-check (not applicable here --
# we are re-running post-processing against existing simulation_data/ case
# directories, not creating a fresh `proteus grid` output directory that
# Grid.__init__ would rmtree), and its confirm pass polls each machine's
# rerun_results.log growing instead of a manager.log progress line.
#
# Usage:
#   scripts/launch_vulcan_reruns.sh [options] <manifest.csv>
#
# Manifest format (as written by generate_vulcan_rerun_configs.py, header
# row required, comments with '#' and blank lines also skipped):
#   machine,launch_script_path,session_name
#   cap001a,/data/.../vulcan_rerun_configs/20260730_140000/cap001a/launch_cap001a.sh,vulcan_rerun_cap001a
#   cap001b,/data/.../vulcan_rerun_configs/20260730_140000/cap001b/launch_cap001b.sh,vulcan_rerun_cap001b
#
# Options:
#   --dry-run                    Run every pre-flight check (script exists,
#                                 busy check) and print exactly what would
#                                 be launched, without ever SSHing a
#                                 tmux/bash launch command.
#   --max-jobs N                  Passed through as each launch_<machine>.sh's
#                                 own MAXJOBS argument (default: 24, matches
#                                 the default baked into the generated
#                                 scripts -- override here to raise/lower it
#                                 for every row in one place without
#                                 regenerating configs).
#   --stagger-seconds N           Delay between launching each row
#                                 (default: 15, same NFS-import-contention
#                                 rationale as launch_batches.sh).
#   --ssh-timeout N                SSH ConnectTimeout, seconds (default: 6).
#   --confirm-timeout-seconds N   How long the final confirm pass polls a
#                                 slow-starting rerun before giving up
#                                 (default: 300).
#   -h, --help                     Show this help and exit.
#
# Examples:
#   scripts/launch_vulcan_reruns.sh --dry-run manifest.csv
#   scripts/launch_vulcan_reruns.sh --max-jobs 12 manifest.csv

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
PROTEUS_DIR="/data/rdc49-2/PROTEUS"

DRY_RUN=0
MAX_JOBS=24
STAGGER_SECONDS=15
SSH_TIMEOUT=6
CONFIRM_TIMEOUT_SECONDS=300
MANIFEST=""

usage() {
    sed -n '2,/^set -euo pipefail/p' "${BASH_SOURCE[0]}" | sed '$d' | sed 's/^# \{0,1\}//'
}

log() {
    printf '%s\n' "$*"
}

die() {
    printf 'ERROR: %s\n' "$*" >&2
    exit 1
}

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------

while [ $# -gt 0 ]; do
    case "$1" in
        --dry-run)
            DRY_RUN=1
            shift
            ;;
        --max-jobs)
            [ $# -ge 2 ] || die "--max-jobs requires a value"
            MAX_JOBS="$2"
            shift 2
            ;;
        --stagger-seconds)
            [ $# -ge 2 ] || die "--stagger-seconds requires a value"
            STAGGER_SECONDS="$2"
            shift 2
            ;;
        --ssh-timeout)
            [ $# -ge 2 ] || die "--ssh-timeout requires a value"
            SSH_TIMEOUT="$2"
            shift 2
            ;;
        --confirm-timeout-seconds)
            [ $# -ge 2 ] || die "--confirm-timeout-seconds requires a value"
            CONFIRM_TIMEOUT_SECONDS="$2"
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        --)
            shift
            break
            ;;
        -*)
            die "Unknown option: $1 (see --help)"
            ;;
        *)
            if [ -n "$MANIFEST" ]; then
                die "Multiple manifest arguments given ('$MANIFEST' and '$1')"
            fi
            MANIFEST="$1"
            shift
            ;;
    esac
done

[ -n "$MANIFEST" ] || { usage; die "No manifest file given"; }
[ -f "$MANIFEST" ] || die "Manifest file not found: $MANIFEST"

if [ "$DRY_RUN" -eq 1 ]; then
    log "[dry-run] no tmux/launch-script commands will actually be sent"
fi

# ---------------------------------------------------------------------------
# Manifest parsing (skip the header row generate_vulcan_rerun_configs.py
# writes: 'machine,launch_script_path,session_name')
# ---------------------------------------------------------------------------

ROW_MACHINE=()
ROW_SCRIPT=()
ROW_SESSION=()
ROW_STATUS=()

lineno=0
while IFS= read -r raw_line || [ -n "$raw_line" ]; do
    lineno=$((lineno + 1))
    line="$(printf '%s' "$raw_line" | tr -d '\r')"
    line="$(printf '%s' "$line" | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//')"

    [ -z "$line" ] && continue
    [[ "$line" == \#* ]] && continue
    [ "$line" = "machine,launch_script_path,session_name" ] && continue

    IFS=',' read -r f_machine f_script f_session <<<"$line"
    f_machine="$(printf '%s' "$f_machine" | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//')"
    f_script="$(printf '%s' "$f_script" | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//')"
    f_session="$(printf '%s' "$f_session" | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//')"

    if [ -z "$f_machine" ] || [ -z "$f_script" ] || [ -z "$f_session" ]; then
        die "Manifest line $lineno: expected 'machine,launch_script_path,session_name', got: $raw_line"
    fi

    ROW_MACHINE+=("$f_machine")
    ROW_SCRIPT+=("$f_script")
    ROW_SESSION+=("$f_session")
    ROW_STATUS+=("")
done <"$MANIFEST"

NUM_ROWS=${#ROW_MACHINE[@]}
[ "$NUM_ROWS" -gt 0 ] || die "Manifest has no launch rows: $MANIFEST"

log "Loaded $NUM_ROWS row(s) from $MANIFEST"
log ""

declare -A MACHINE_CHECKED_THIS_RUN

# ---------------------------------------------------------------------------
# Per-row pre-flight + launch
# ---------------------------------------------------------------------------

for i in "${!ROW_MACHINE[@]}"; do
    machine="${ROW_MACHINE[$i]}"
    launch_script_rel="${ROW_SCRIPT[$i]}"
    session="${ROW_SESSION[$i]}"
    case "$launch_script_rel" in
        /*) launch_script="$launch_script_rel" ;;
        *) launch_script="$PROJECT_ROOT/$launch_script_rel" ;;
    esac

    log "== Row $((i + 1))/$NUM_ROWS: $machine / $launch_script / $session =="

    # --- 1. launch script exists? ---
    if [ ! -f "$launch_script" ]; then
        log "  ABORTED: launch script not found: $launch_script"
        ROW_STATUS[$i]="ABORTED (script not found)"
        log ""
        continue
    fi

    # --- 2. busy check (skip if this machine already checked/used this run) ---
    if [ -n "${MACHINE_CHECKED_THIS_RUN[$machine]:-}" ]; then
        log "  Busy check skipped: $machine already used earlier in this run"
    else
        ssh_rc=0
        ps_output="$(ssh -o ConnectTimeout="$SSH_TIMEOUT" -o BatchMode=yes "$machine" \
            "uptime; ps aux --sort=-%cpu | grep -Ei 'python|julia|proteus|agni|spider' | grep -v grep" \
            2>&1)" || ssh_rc=$?

        if [ "$ssh_rc" -ne 0 ] && [ -z "$ps_output" ]; then
            log "  SKIPPED: could not reach $machine over SSH"
            ROW_STATUS[$i]="SKIPPED (unreachable)"
            log ""
            continue
        fi

        # Exclude leftover empty tmux wrapper processes from a finished batch
        # (e.g. `tmux new-session -d -s proteus_batch16 -c /data/rdc49-2/PROTEUS`)
        # -- these hold no running job, but their own command line matches
        # 'proteus' just from the session name/directory, giving a false
        # positive busy reading.
        busy_lines="$(printf '%s\n' "$ps_output" | grep -v '^root ' | grep -v 'tmux new-session' | grep -Ei 'python|julia|proteus|agni|spider' || true)"
        if [ -n "$busy_lines" ]; then
            log "  SKIPPED: $machine appears busy with a non-root process:"
            printf '%s\n' "$busy_lines" | sed 's/^/    /'
            ROW_STATUS[$i]="SKIPPED (machine busy)"
            log ""
            continue
        fi
        log "  $machine confirmed idle."
    fi
    MACHINE_CHECKED_THIS_RUN[$machine]=1

    # --- 3. launch ---
    if [ "$DRY_RUN" -eq 1 ]; then
        log "  [dry-run] would launch tmux session '$session' on $machine running:"
        log "    bash $launch_script $MAX_JOBS"
        ROW_STATUS[$i]="DRY-RUN (would launch)"
    else
        ssh "$machine" "tmux new-session -d -s '$session' -c $PROTEUS_DIR \
            && tmux send-keys -t '$session' 'module load netcdf/4-2025.01' C-m \
            && sleep 2 \
            && tmux send-keys -t '$session' 'conda activate proteus' C-m \
            && sleep 3 \
            && tmux send-keys -t '$session' 'bash $launch_script $MAX_JOBS' C-m"
        log "  Launched tmux session '$session' on $machine (max $MAX_JOBS concurrent)."
        ROW_STATUS[$i]="LAUNCHED"
    fi

    log ""

    # --- 4. stagger ---
    is_last_row=$((i == NUM_ROWS - 1))
    if [ "$is_last_row" -eq 0 ] && [ "$DRY_RUN" -eq 0 ] && [ "$STAGGER_SECONDS" -gt 0 ]; then
        log "Sleeping ${STAGGER_SECONDS}s before the next row (NFS-contention stagger)..."
        sleep "$STAGGER_SECONDS"
        log ""
    fi
done

# ---------------------------------------------------------------------------
# Final confirm pass -- poll each launched row's rerun_results.log for the
# first line to appear (i.e. at least one case has finished, success or not)
# ---------------------------------------------------------------------------

if [ "$DRY_RUN" -eq 0 ]; then
    log "=============================================================="
    log "Confirm pass: polling rerun_results.log for launched rows (up to ${CONFIRM_TIMEOUT_SECONDS}s each)"
    log "=============================================================="

    for i in "${!ROW_MACHINE[@]}"; do
        [ "${ROW_STATUS[$i]}" = "LAUNCHED" ] || continue

        machine="${ROW_MACHINE[$i]}"
        session="${ROW_SESSION[$i]}"
        launch_script_rel="${ROW_SCRIPT[$i]}"
        case "$launch_script_rel" in
            /*) launch_script="$launch_script_rel" ;;
            *) launch_script="$PROJECT_ROOT/$launch_script_rel" ;;
        esac
        results_log="$(dirname "$launch_script")/rerun_results.log"

        log "-- Confirming $session ($results_log) --"
        elapsed=0
        poll_interval=15
        confirmed=0
        while [ "$elapsed" -lt "$CONFIRM_TIMEOUT_SECONDS" ]; do
            if [ -f "$results_log" ] && [ -s "$results_log" ]; then
                confirmed=1
                break
            fi
            sleep "$poll_interval"
            elapsed=$((elapsed + poll_interval))
        done

        if [ "$confirmed" -eq 1 ]; then
            log "  Confirmed: at least one result recorded in $results_log"
            ROW_STATUS[$i]="LAUNCHED (confirmed)"
        else
            log "  UNCERTAIN: no result recorded in $results_log within"
            log "  ${CONFIRM_TIMEOUT_SECONDS}s. offchem+observe can genuinely take"
            log "  this long per case (VULCAN's kinetics solve alone can run tens"
            log "  of minutes) -- check manually before assuming failure:"
            log "    ssh $machine \"tmux capture-pane -t $session -p | tail -20\""
            ROW_STATUS[$i]="UNCERTAIN (check manually)"
        fi
        log ""
    done
fi

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

log "=============================================================="
log "Summary"
log "=============================================================="
for i in "${!ROW_MACHINE[@]}"; do
    printf '  %-10s %-60s %-25s %s\n' \
        "${ROW_MACHINE[$i]}" "${ROW_SCRIPT[$i]}" "${ROW_SESSION[$i]}" "${ROW_STATUS[$i]}"
done
