# Batch 26 of 32 -- K218b main parameter sweep
# Full sweep definition: ../full_parameter_sweep.toml
# This batch: fO2_shift_IW = 0 ; H_budget = low half [1.00e4, 1.71e4] ; C_budget = 0.032
# Grid size: 1 (fO2) x 2 (H_budget) x 1 (C_budget) x 4 (N_budget) x 4 (S_budget) = 32 points

output = "k218b_project_main_parameter_sweep_batch26/"
symlink = ""

ref_config = "input/nogit_k218b_project/k218b_fiducial.toml"

use_slurm = false
max_jobs = 500
max_days = 1
max_mem  = 3

["planet.elements.H_budget"]
    method = "direct"
    values = [10000.0,17099.75946676698]

["planet.elements.C_budget"]
    method = "direct"
    values = [0.032]

["planet.elements.N_budget"]
    method = "direct"
    values = [0.0009,0.009,0.09,0.9]

["planet.elements.S_budget"]
    method = "direct"
    values = [0.004,0.04,0.4,4.0]

["outgas.fO2_shift_IW"]
    method = "direct"
    values = [0.0]
