# Batch 1 of 8 -- K218b main parameter sweep
# Full sweep definition: ../full_parameter_sweep.toml
# This batch: fO2_shift_IW = -3 ; H_budget = low half [1.00e4, 1.71e4]
# Grid size: 1 (fO2) x 2 (H_budget) x 4 (C_budget) x 4 (N_budget) x 4 (S_budget) = 128 points

output = "k218b_project_main_parameter_sweep_batch01/"
symlink = ""

ref_config = "input/nogit_k218b_project/k218b_fiducial.toml"

use_slurm = false
max_jobs = 500
max_days = 1
max_mem  = 3

["planet.elements.H_budget"]
    method = "direct"
    values = [10000.0,17099.75946676698]

["planet.elements.C_budget"]
    method = "direct"
    values = [3.2e-3,3.2e-2,3.2e-1,3.2e0]

["planet.elements.N_budget"]
    method = "direct"
    values = [9e-4,9e-3,9e-2,9e-1]

["planet.elements.S_budget"]
    method = "direct"
    values = [4e-3,4e-2,4e-1,4e0]

["outgas.fO2_shift_IW"]
    method = "direct"
    values = [-3]
